# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  # important: apparently this section CANNOT be spun off into its own yaml file!
  auth_providers:
    # trust Authelia to handle authentication, see:
    # https://github.com/authelia/authelia/discussions/4681
    - type: command_line
      command: /config/auth.sh
      args: ["auth.jrvs.io"]
      meta: true
    # keeping regular HA auth for now just in case authelia breaks, that would be bad...
    - type: homeassistant

# random one-offs which require manual activation:
ffmpeg:
wake_on_lan:

# all other configurations are in the following yaml files:
automation: !include automations.yaml
cover: !include cover.yaml
frontend: !include frontend.yaml
http: !include http.yaml
influxdb: !include influxdb.yaml
logger: !include logger.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
lovelace: !include ui-lovelace.yaml
