blueprint:
  domain: automation
  name: Philips Hue v2 Smart Dimmer Switch and Remote
  description:
    Philips Hue v2 Smart Dimmer Switch and Remote (RWL022) using Zigbee
    Home Automation
  input:
    zha_device:
      name: Philips Hue v2 Smart Dimmer Switch and Remote
      description:
        List of available Philips Hue v2 Smart Dimmer Switch and Remote
        devices
      selector:
        device:
          integration: zha
          model: RWL022
          multiple: false
    Power_Press:
      name: Power Press
      description: Power button pressed
      default: []
      selector:
        action: {}
    Power_Press2x:
      name: Power Press 2x
      description: Power button pressed 2x
      default: []
      selector:
        action: {}
    Power_Press3x:
      name: Power Press 3x
      description: Power button pressed 3x
      default: []
      selector:
        action: {}
    Power_Press4x:
      name: Power Press 4x
      description: Power button pressed 4x
      default: []
      selector:
        action: {}
    Power_Press5x:
      name: Power Press 5x
      description: Power button pressed 5x
      default: []
      selector:
        action: {}
    Power_Release:
      name: Power Release
      description: Power button released
      default: []
      selector:
        action: {}
    Power_HoldPress:
      name: Power Hold
      description: Power button held down
      default: []
      selector:
        action: {}
    Power_HoldRelease:
      name: Power Hold Release
      description: Power button released after held down
      default: []
      selector:
        action: {}
    Up_Press:
      name: Up Press
      description: Up button pressed
      default: []
      selector:
        action: {}
    Up_Press2x:
      name: Up Press 2x
      description: Up button pressed 2x
      default: []
      selector:
        action: {}
    Up_Press3x:
      name: Up Press 3x
      description: Up button pressed 3x
      default: []
      selector:
        action: {}
    Up_Press4x:
      name: Up Press 4x
      description: Up button pressed 4x
      default: []
      selector:
        action: {}
    Up_Press5x:
      name: Up Press 5x
      description: Up button pressed 5x
      default: []
      selector:
        action: {}
    Up_Release:
      name: Up Release
      description: Up button released
      default: []
      selector:
        action: {}
    Up_HoldPress:
      name: Up Hold
      description: Up button held down
      default: []
      selector:
        action: {}
    Up_HoldRelease:
      name: Up Hold Release
      description: Up button released after held down
      default: []
      selector:
        action: {}
    Down_Press:
      name: Down Press
      description: Down button pressed
      default: []
      selector:
        action: {}
    Down_Press2x:
      name: Down Press 2x
      description: Down button pressed 2x
      default: []
      selector:
        action: {}
    Down_Press3x:
      name: Down Press 3x
      description: Down button pressed 3x
      default: []
      selector:
        action: {}
    Down_Press4x:
      name: Down Press 4x
      description: Down button pressed 4x
      default: []
      selector:
        action: {}
    Down_Press5x:
      name: Down Press 5x
      description: Down button pressed 5x
      default: []
      selector:
        action: {}
    Down_Release:
      name: Down Release
      description: Down button released
      default: []
      selector:
        action: {}
    Down_HoldPress:
      name: Down Hold
      description: Down button held down
      default: []
      selector:
        action: {}
    Down_HoldRelease:
      name: Down Hold Release
      description: Down button released after held down
      default: []
      selector:
        action: {}
    Hue_Press:
      name: Hue Press
      description: Hue button pressed
      default: []
      selector:
        action: {}
    Hue_Press2x:
      name: Hue Press 2x
      description: Hue button pressed 2x
      default: []
      selector:
        action: {}
    Hue_Press3x:
      name: Hue Press 3x
      description: Hue button pressed 3x
      default: []
      selector:
        action: {}
    Hue_Press4x:
      name: Hue Press 4x
      description: Hue button pressed 4x
      default: []
      selector:
        action: {}
    Hue_Press5x:
      name: Hue Press 5x
      description: Hue button pressed 5x
      default: []
      selector:
        action: {}
    Hue_Release:
      name: Hue Release
      description: Hue button released
      default: []
      selector:
        action: {}
    Hue_HoldPress:
      name: Hue Hold
      description: Hue button held down
      default: []
      selector:
        action: {}
    Hue_HoldRelease:
      name: Hue Hold Release
      description: Hue button released after held down
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
variables:
  device_id: !input zha_device
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zha_device
condition: "{{ trigger.event.data.device_id == device_id }}"
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
  - choose:
      - conditions: '{{ command == "on_press" }}'
        sequence: !input Power_Press
      - conditions: '{{ command == "on_double_press" }}'
        sequence: !input Power_Press2x
      - conditions: '{{ command == "on_triple_press" }}'
        sequence: !input Power_Press3x
      - conditions: '{{ command == "on_quadruple_press" }}'
        sequence: !input Power_Press4x
      - conditions: '{{ command == "on_quintuple_press" }}'
        sequence: !input Power_Press5x
      - conditions: '{{ command == "on_short_release" }}'
        sequence: !input Power_Release
      - conditions: '{{ command == "on_hold" }}'
        sequence: !input Power_HoldPress
      - conditions: '{{ command == "on_long_release" }}'
        sequence: !input Power_HoldRelease
      - conditions: '{{ command == "up_press" }}'
        sequence: !input Up_Press
      - conditions: '{{ command == "up_double_press" }}'
        sequence: !input Up_Press2x
      - conditions: '{{ command == "up_triple_press" }}'
        sequence: !input Up_Press3x
      - conditions: '{{ command == "up_quadruple_press" }}'
        sequence: !input Up_Press4x
      - conditions: '{{ command == "up_quintuple_press" }}'
        sequence: !input Up_Press5x
      - conditions: '{{ command == "up_short_release" }}'
        sequence: !input Up_Release
      - conditions: '{{ command == "up_hold" }}'
        sequence: !input Up_HoldPress
      - conditions: '{{ command == "up_long_release" }}'
        sequence: !input Up_HoldRelease
      - conditions: '{{ command == "down_press" }}'
        sequence: !input Down_Press
      - conditions: '{{ command == "down_double_press" }}'
        sequence: !input Down_Press2x
      - conditions: '{{ command == "down_triple_press" }}'
        sequence: !input Down_Press3x
      - conditions: '{{ command == "down_quadruple_press" }}'
        sequence: !input Down_Press4x
      - conditions: '{{ command == "down_quintuple_press" }}'
        sequence: !input Down_Press5x
      - conditions: '{{ command == "down_short_release" }}'
        sequence: !input Down_Release
      - conditions: '{{ command == "down_hold" }}'
        sequence: !input Down_HoldPress
      - conditions: '{{ command == "down_long_release" }}'
        sequence: !input Down_HoldRelease
      - conditions: '{{ command == "off_press" }}'
        sequence: !input Hue_Press
      - conditions: '{{ command == "off_double_press" }}'
        sequence: !input Hue_Press2x
      - conditions: '{{ command == "off_triple_press" }}'
        sequence: !input Hue_Press3x
      - conditions: '{{ command == "off_quadruple_press" }}'
        sequence: !input Hue_Press4x
      - conditions: '{{ command == "off_quintuple_press" }}'
        sequence: !input Hue_Press5x
      - conditions: '{{ command == "off_short_release" }}'
        sequence: !input Hue_Release
      - conditions: '{{ command == "off_hold" }}'
        sequence: !input Hue_HoldPress
      - conditions: '{{ command == "off_long_release" }}'
        sequence: !input Hue_HoldRelease
